language: ruby

services:
  - docker

before_install:
  - docker build -t melovemingming/crm .
  - docker run -d -p 80:8080 melovemingming/crm
  - docker ps -a
  - echo "ABCcba20170607" | docker login -u "melovemingming" --password-stdin
  - docker push melovemingming/crm

